name: edu_site_server
description: Starting point for a Serverpod server.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  serverpod: 1.2.6
  pubspec_yaml: ^3.1.0

dev_dependencies:
  lints: ^3.0.0
